Activate dynamic variant filtering for 'validate' variant calling
cyclomics/cyclomicsseq pull request #23
Opened 2023-10-31 14:33 UTC by groodri

- activate dynamic variant filtering for vc `validate`
- ammended how the AO tag is written in vc `validate`: in accordance with freebayes, the tag stands for the sum of qualities of the alternative allele
- ammended user options in epi2me interface

2023-10-31 16:05 UTC, da-i commented on bin/variant_calling/detect_indel.py
> +                for k, v in result[3].items():
This code is very ambiguous, just reading this we could be doing anything.

2023-10-31 16:07 UTC, da-i commented on bin/variant_calling/detect_indel.py
> +                for k, v in result[3].items():
e.g. if k and v had more meaning full names it would b clear what we are doing here

2023-10-31 16:09 UTC, da-i requested changes
Overall clearly an improvement. some code is a bit ambiguous, as mentioned in one example. Lets think this through for the next big refactor & testing effort. Please fix these minor items and go ahead and merge yourself!

2023-10-31 16:09 UTC, da-i commented on bin/variant_calling/detect_snp.py
> +            print("hi")
Hello :)

2023-11-01 14:09 UTC, groodri commented on bin/variant_calling/detect_indel.py
> +                for k, v in result[3].items():
Changed:
- k = info_tag
- v = value
- added comments to explain this section

2023-11-01 14:09 UTC, groodri commented on bin/variant_calling/detect_snp.py
> +            print("hi")
Oops!

2023-11-01 14:13 UTC, merged